@{
    RootModule        = 'cmdpeek.psm1'
    ModuleVersion     = '0.2.0'
    GUID              = '8f3c2a91-4e6b-4d7a-9c1e-2b8f6a0d5e31'
    Author            = 'cmdpeek contributors'
    CompanyName       = 'cmdpeek'
    Copyright         = '(c) cmdpeek contributors. MIT License.'
    Description       = 'Show recently installed CLI commands and match tasks to tools you already have.'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'Get-CmdPeekPackageManager'
        'Get-CmdPeekPackageManagerInstallHint'
        'Get-CmdPeekInstalledPackage'
        'Get-CmdPeekCommandHistory'
        'Get-CmdPeekUnknownInstallDate'
        'Find-CmdPeekMissingCommand'
        'Search-CmdPeekCommand'
        'Select-CmdPeekExactCommand'
        'Get-CmdPeekState'
        'Save-CmdPeekState'
        'Set-CmdPeekFavorite'
        'Set-CmdPeekHidden'
        'Set-CmdPeekPreferredPackageManager'
        'Export-CmdPeekState'
        'Import-CmdPeekState'
        'ConvertTo-CmdPeekState'
        'Get-CmdPeekUsageExample'
        'Get-CmdPeekExampleCatalog'
        'Get-CmdPeekCatalogKits'
        'Invoke-CmdPeek'
        'Invoke-CmdPeekInteractive'
        'Format-CmdPeekQuickOutput'
        'Install-CmdPeekTrackedPackage'
        'Get-CmdPeekGap'
        'Get-CmdPeekGapKind'
        'Get-CmdPeekGapKindRank'
        'Get-CmdPeekGapSummary'
        'Select-CmdPeekGap'
        'Get-CmdPeekInventory'
        'ConvertTo-CmdPeekSnapshot'
        'Add-CmdPeekProfileHint'
        'Convert-CmdPeekSince'
        'Select-CmdPeekJustInstalled'
        'Get-CmdPeekRusty'
        'Resolve-CmdPeekTask'
        'Get-CmdPeekWhyCommand'
        'Get-CmdPeekHaveList'
        'Search-CmdPeekAvailable'
        'Test-CmdPeekCatalog'
        'Get-CmdPeekLastInstall'
        'Get-CmdPeekInstallCommands'
        'Test-CmdPeekShellBuiltinName'
        'Add-CmdPeekPathCommands'
        'Format-CmdPeekTaskOutput'
        'Format-CmdPeekWhyOutput'
        'Format-CmdPeekHaveOutput'
        'Get-CmdPeekAptPackage'
        'Get-CmdPeekAptPackageCommand'
        'Get-CmdPeekAptFileListMap'
        'Get-CmdPeekPacmanPackage'
        'Get-CmdPeekWinGetReleaseInfo'
        'Get-CmdPeekMockAiExample'
        'Get-CmdPeekOpenAiExample'
        'Get-CmdPeekRustyLastUsedPath'
        'Save-CmdPeekRustyLastUsed'
        'Write-CmdPeekRustyLastUsedLine'
        'Add-CmdPeekHistoryTimestamp'
        'Get-CmdPeekDefaultUnixRoot'
        'Format-CmdPeekGapOutput'
        'Format-CmdPeekAgentExport'
        'Get-CmdPeekCommandCard'
        'Compare-CmdPeekCommand'
        'Get-CmdPeekArgvSuggestion'
        'Get-CmdPeekSystemList'
        'Test-CmdPeekCatalogIsBuiltin'
        'Get-CmdPeekCurrentOs'
        'Save-CmdPeekLearnedCatalogEntry'
        'Get-CmdPeekVersion'
        'Get-CmdPeekModuleVersion'
        'Get-CmdPeekMcpVersion'
        'Get-CmdPeekDoctorReport'
        'Format-CmdPeekDoctorReport'
        'Measure-CmdPeekScanStage'
        'Get-CmdPeekInventoryCache'
        'Save-CmdPeekInventoryCache'
        'Get-CmdPeekInventoryCachePath'
        'Get-CmdPeekInventoryCacheSeconds'
        'Test-CmdPeekCatalogFile'
        'Test-CmdPeekJsonSchema'
        'Get-CmdPeekCatalogCoverage'
        'Format-CmdPeekCatalogLint'
        'Invoke-CmdPeekCatalogLint'
        'Get-CmdPeekCatalogFileList'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData       = @{
        PSData = @{
            Tags         = @('windows', 'cli', 'scoop', 'chocolatey', 'winget', 'pipx', 'mcp', 'packages')
            LicenseUri   = 'https://opensource.org/licenses/MIT'
            ProjectUri   = 'https://github.com/UnspokenMallard/cmdpeek'
            ReleaseNotes = '0.2.0: task resolver (prefer installed), extra scanners, catalog overlay, MCP prompts/resources.'
        }
    }
}
